### ISSUE TITLE
UI Considerations

### ISSUE THREAD

**Issue by farski** [PRX/dovetail-insights#1]
## Lens Select

The Data Explorer always operates as some specific _lens_. The purpose of lenses, and the way the Explorer operates for any given lens, tend to be fairly similar, but there are important differences. There are differences both in what inputs are required from the user to generate results, and how those results are displayed.

For example, one lens may be able to generate results as both a table and a chart, while some other lens may never be able to display results as a chart. One lens may require that the user select a period like "daily" or "monthly", and another lens may have no concept of periods like that.

From a user standpoint, selecting the lens is probably the first thing that should happen. We should decide if it's possible for the lens selection to change after that.

The UI should anticipate between 4 and 6 lens types to start, but that could change over time and the UI should accomodate growth.

The UI does not need to be able to specifically handle cases where someone has changed the lens type in the URL after constructing a query. It should validate the inputs for the new lens as it normally would.

## Time Range Input

The Data Explorer always requires a time range to generate results. The user defines a time range by selecting a start and end values. These values can either be absolute values or relative values. The backend allows a range to mix absolute and relative values.

When setting relative values, the backend expects values that take the form of an expression like `now`, `now/Y`, `now-1/Y` or `now-2/M+15D+12h`. These expressions can get a bit long and complicated, but their usefulness comes from their flexibility, so users should be able to enter them and tweak them directly in some way, even if that's not the default way they are surfaced in the UI. When a user is inputting relative value expressions, there should be some affordance to let them check that the expression is doing what they want (i.e., somehow show the date and time that the expression resolves to, or describe the expression in words.).

When setting absolute values, the backend expects values that take the form `2024-06-19T12:34:56Z` and represent an instant in time, without any partial seconds. The backend will also automatically interpret `2024-06-19` as `2024-06-19T00:00:00Z`. The backend always and only uses UTC.

The UI for inputting absolute values could allow the user to ignore hours/minutes/seconds if they are not needed, or we omit hours/minutes/seconds entirely, and start by only offering date inputs. The UI could allow the user to select values in a time zone other than UTC, but those values would need to be correctly converted prior to being passed to the backend.

The UI should be able to handle values that aren't necessarily possible to select with the UI. For example, the UI may not directly offer mixing absolute and relative values, but someone could change the URL to create that situation, and since it's supported by the backend, it should be supported by the UI as well.

The backend **always** treats the passed start value as inclusive, and the passed end value as exclusive. There's no requirement for the UI to appear to work that way. For example, we may want the user to be able to select start=June 1, end=June 30 to select the entire month of June (rather than start=June 1, and end=July 1). As long as the June 30th user input is correctly transposed to `2024-07-01T00:00:00Z` before it's passed to the backend, that's fine. (Same thing for when the page loads after the end value has already been set, it would need to know to transpose `2024-07-01T00:00:00Z` to June 30 in the UI.) If/when the end values include a time component, this sort of transposition doesn't really make any sense.

The UI should offer some standard, common ranges that the user can select to fill in the start and end values (things like: `Previous 7 days`, `Previous week`, `Previous month`, `This year`, etc). It should be clear to the user if the values being filled in are absolute or relative.

## Filters

All lenses support filters, and all lenses support the same possible filters and in the same way(s). The UI for filters probably should not change based on lens selection.

Filters are based on dimensions of the data (things like _user agent_, _country_, etc.). Any given dimension can have at most one filter (meaning, at no point could two _user agent_ filters be added).

Filters are optional, and the user should not have to select any filters to successfully query some data. (Worth noting that, internally, the backend will almost always do some filtering, based on the user's authorization and permissions, such as which podcasts they have access to, even if the user does not add a filter based on the podcast dimension).

All filters operate as either _include_ or _exclude_.

The nature of dimension determine the way or ways in which the filter for that dimension function, and what inputs are needed from the user.

For example, a dimension like _podcast_ may have a filter that allows the user to select which podcasts to include (or exclude) in the resulting data. This filter represents a list of one or more podcasts. Something like defining a range wouldn't make sense for the _podcast_ dimension. Conversely, a dimension like _publish date_ may have a filter that allows the user to include (or exclude) data for only a set of episodes published during a certain window. In this case, it does make sense for the filter to allow the user to select a range.

The UI for filters should allow for this variability, without becoming overwhelming.

The UI should anticipate at least 20 dimensions being available for filtering, but that number will grow over time.

A user may add no filters, or will likely often add between 1 and 3 filters, or may rarely add many filters. The UI shouldn't dedicate unnecessary space for filters, but should cleanly accomodate cases where many filters have been added.

The user should be able to disable a filter, without removing it and its configuration entirely.

A filter may be able to operate in multiple modes. For example, a filter for the _publish date_ dimension, in addition to a range input, may also allow the user to include only episodes that were publised on a particular day (or days) of the week, like only Saturday and Sunday. Other filters, like the _podcast_ filter, may only operate in one mode.

Or… a _podcast_ filter may only operate in one "select" mode today, but later we may add an additional mode for that dimension. Something like `starts with`, where the user can include podcasts whose names start with a particular string.

The point is that we should create a UI that allows us to introduce new filter functionality without much friction over time.

At this stage of development, the focus should be on creating a UI that nicely handles:
- the number of dimensions available for filtering
- the variety of filters that a user may add
- enabling and disabling filters
- the ability for a user to choose which mode a filter is operating in, if that's available
- inputting necessary data for the chosen mode
- form validations/warnings that are specific to the filter and even specific elements within that filter's UI, to help a user resolve data input issues

All the various UIs for different modes of different dimension types are not being defined at this time – the system being design should be able to handle a wide variety of what those UIs may end up looking like, and not break down as additiong filter mode UIs are added over time.

In general, though, the filter UIs will need to support things like:
- standard form controls, like selects, check boxes or radio buttons to define behavior.
- selecting an option or multiple options from a dynamic list (like a country or countries), with conveniences like type incremental search, select all, select none, etc
- define ranges – both numeric and time ranges. time ranges should support similar functionality to the overall time range selection discussed above, like relative and absolute dates, etc.

A user may select a value in a filter, such as a podcast in the _podcast_ filter, and when they revisit the page (such as if they bookmarked it), they may no longer have access to that podcast (because their authorization or permissions changed). The backend will validate these situations, but if the UI can catch those things earlier (like if the UI loads the list of available podcasts and sees that the selected one is not included), that could be helpful.

**Comment by brandonhundt** [comment]
Thanks for this @farski. I appreciate you outlining your thoughts here, so we can reference them in the design phase. Also, I think we have a lot of existing elements in our shared styles that we can leverage to design this UI to ensure it remains intuitive.

**Comment by brandonhundt** [comment]
Closing in favor of #2

**Comment by farski** [comment]
@brandonhundt if you have any time this sprint to spend on Insights, the filters UX is something I still haven't been able to spend much time getting into the weeds on and where I have the fewest good ideas for solving some of the complexities. I don't know exactly what the UI will look like for managing all the filters on the page, but I think there is some good prior art for that sort of thing, so that's probably not the priority. The area that really needs some focus is the UI for interacting with a -single filter and all of its various options and permutations. If you do have time to spend on that and need more info that what's described above, or specific examples/screenshots, let me know.

**Comment by brandonhundt** [comment]
Yes, I can take some time this sprint to hone in on specific filters.
